### ISSUE TITLE
Improvement: Alert looks compact in large size devices.

### ISSUE THREAD

**Issue by jpvinod** [therohansanap/RSBlurAlert#1]
This is just improvement. In large size devices alert looks compact if it's looks little wide then it'll look good.

**Comment by therohansanap** [comment]
@vinodiOS Which devices have you considered in this issue context? Bigger iPhones or iPads?

**Comment by jpvinod** [comment]
I did it in iPhone 8. See the description label looks compact if alert size matches the width of screen then it would look good.

**Comment by jpvinod** [comment]
By giving aspect ratio to outer visual effect view, it might help.
