### ISSUE TITLE
How to show full background also blur

### ISSUE THREAD

**Issue by muga87** [therohansanap/RSBlurAlert#3]
Hi ,
This is very cool. How to make total background also blur?

**Comment by therohansanap** [comment]
Blurring complete background will defy the purpose of having "macOS style" alert. Hence, I am afraid this is not a feature of this component.

Yet if you want to achieve what you have requested, you can do that by adding a full screen  UIVisulaEffectView to your viewcontroller (from which you are presenting) before presenting RSBlurAlert.
